### ISSUE TITLE
The output file do not contain the component of xVec.

### ISSUE THREAD

**Issue by dadeba** [nakatamaho/sdpa-binary128#1]
The output file for "example1.dat"
<img width="595" alt="スクリーンショット 2023-04-05 9 40 19" src="https://user-images.githubusercontent.com/414056/229955716-a2983ebc-140f-4ed9-84f1-00af6a9b578f.png">

**Comment by nakatamaho** [comment]
it looks the following line does not output the result.
     currentPt.yVec.display(fpout,-1.0);

diff --git a/sdpa_io.cpp b/sdpa_io.cpp
index b146eb3..f84f3b5 100644
--- a/sdpa_io.cpp
+++ b/sdpa_io.cpp
@@ -1352,7 +1352,7 @@ void IO::printLastInfo(int pIteration,

     #if 1
     #if REVERSE_PRIMAL_DUAL
-    fprintf(fpout,"xVec = \n");
+    fprintf(fpout,"xVec = \n"); //issue #1
     currentPt.yVec.display(fpout,-1.0);
     fprintf(fpout,"xMat = \n");
     displayDenseLinarSpaceLast(currentPt.zMat,
